### ISSUE TITLE
Compatibility with PyMySQL == 0.9.0

### ISSUE THREAD

**Issue by LilyMaster** [aio-libs/aiomysql#302]
PyMySQL has been updated to 0.9.0 and has some incompatible changes. Namely, I get error:
```
lib/python3.6/site-packages/aiomysql/__init__.py:32: in <module>
    from .connection import Connection, connect
lib/python3.6/site-packages/aiomysql/connection.py:30: in <module>
    from pymysql.connections import _scramble
ImportError: cannot import name '_scramble'
```

**Comment by marcoceppi** [comment]
For those experiencing this, on a lovely Wednesday, pin `PyMySQL` to 0.8.1 in your setup / requirements.txt

```
PyMySQL==0.8.1
```

**Comment by arnulfojr** [comment]
And this one is related to https://github.com/aio-libs/aiomysql/issues/297, if I'm not mistaken :)

**Comment by marcoceppi** [comment]
Pretty likely, the biggest issue is the way dependencies are described in this repository. They should really be pinned like

```
PyMySQL>=0.7.5,<0.9
```

The second comparison should be increased when the library is tested with each successive version of  of PyMySQL. This will prevent things like a new library adding a breaking change from catching users off guard. I'll submit a PR to do just that and hopefully a patch can be cut until a more permanent patch to make this library work with PyMySQL 0.9.0

**Comment by arnulfojr** [comment]
Yea, the thing is that the release just went live some hours ago, check it out https://github.com/PyMySQL/PyMySQL/releases unfortunately we are one of the firsts to get the issue.
Quick fix should be the version limitation, proper fix should be to update the code.
Let's wait and see what the members say about it, I guess

**Comment by thesamet** [comment]
Workaround: add PyMySQL==0.7.5 to your project requirements.

**Comment by arnulfojr** [comment]
@thesamet the issue is with the latest `0.9.0` so you are safe of using the `0.8.1` as well :)

**Comment by marcoceppi** [comment]
@arnulfojr To be fair, this project is getting hit with this because PyMySQL was open ended `>=` whereas the rest of the dependencies (esp in requirements-dev) are `==`. While not a absolute, a best practice is to do explicit pinning using either `==` or an upper limit. My workaround is minor, but it'll stop peoples builds from failing.

I absolutely agree aiomysql should work with 0.9 and MySQL 8 but that's likely a larger patch set.

**Comment by arnulfojr** [comment]
@marcoceppi totally agree :)

**Comment by and800** [comment]
> I absolutely agree aiomysql should work with 0.9 and MySQL 8 **but that's likely a larger patch set.**

I don't think it is so hard. We should stop using pymysql's private api. Instead, we can for example copypaste its private objects into `vendor` dir, so they won't be changed by minor updates

**Comment by terrycain** [comment]
Have MySQL 8 / sha256 support here https://github.com/terrycain/aiomysql/tree/sha256, will pr it after #309. Just thought I'd drop it incase its useful
