### PR TITLE
Remove deprecated loop argument for python 3.10

### LINKED ISSUE #505: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
Any plans to fix this deprecation warning?

```
root/.local/share/virtualenvs/app-ueEJiAOq/lib/python3.8/site-packages/aiomysql/pool.py:46: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
    self._cond = asyncio.Condition(loop=loop)
/usr/local/lib/python3.8/asyncio/locks.py:335: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
    lock = Lock(loop=loop)
/usr/local/lib/python3.8/asyncio/tasks.py:455: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
   return await fut
```

### LINKED ISSUE #630: aiomysql doesn't work with python3.10
/home/xxxx//test.py:23: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Traceback (most recent call last):
  File "/home/xxxx/.local/lib/python3.10/site-packages/aiomysql/connection.py", line 486, in _connect
    self._reader, self._writer = await \
  File "/usr/lib64/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/lib64/python3.10/asyncio/streams.py", line 47, in open_connection
    transport, _ = await loop.create_connection(
TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'loop'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xxxx/test.py", line 24, in <module>
    loop.run_until_complete(test_example(loop))
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/xxxx/test.py", line 7, in test_example
    conn = await aiomysql.connect(
  File "/home/xxxx/.local/lib/python3.10/site-packages/aiomysql/connection.py", line 75, in _connect
    await conn._connect()
  File "/home/xxxx/.local/lib/python3.10/site-packages/aiomysql/connection.py", line 521, in _connect
    raise OperationalError(2003,
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'xxxxx.rds.amazonaws.com'")

it works with python3.8

### PR DESCRIPTION
**Pull request by albertyw**
## What do these changes do?

This PR removes usage of the `loop` argument to allow aiomysql to run with python 3.10.  The `loop` argument has been deprecated since python 3.8 and removed in python 3.10.  

## Are there changes in behavior for the user?

This should be fully backwards compatible.  There should be no changes in behavior.

## Related issue number

Fixes #505 
Fixes #630 

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Review by asvetlov — APPROVED** [review]

**Comment by asvetlov** [comment]
Thanks!

**Comment by asvetlov** [comment]
aiomysql 0.0.22 released.

Sorry, I have no capacity for the full project support, many issues and pull requests still are present.

**Comment by lein** [comment]
> aiomysql 0.0.22 released.

Hi @asvetlov. Thank you for merging, but 0.0.22 actually has not yet released, probably corresponding tag is needed.

**Comment by asvetlov** [comment]
https://pypi.org/project/aiomysql/

CI is broken, I've pushed distributions manually.
Added a tag for consistency.
