### ISSUE TITLE
aiomysql doesn't work with python3.10 

### ISSUE THREAD

**Issue by DrunkRandomWalker** [aio-libs/aiomysql#630]
/home/xxxx//test.py:23: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Traceback (most recent call last):
  File "/home/xxxx/.local/lib/python3.10/site-packages/aiomysql/connection.py", line 486, in _connect
    self._reader, self._writer = await \
  File "/usr/lib64/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/lib64/python3.10/asyncio/streams.py", line 47, in open_connection
    transport, _ = await loop.create_connection(
TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'loop'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xxxx/test.py", line 24, in <module>
    loop.run_until_complete(test_example(loop))
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/xxxx/test.py", line 7, in test_example
    conn = await aiomysql.connect(
  File "/home/xxxx/.local/lib/python3.10/site-packages/aiomysql/connection.py", line 75, in _connect
    await conn._connect()
  File "/home/xxxx/.local/lib/python3.10/site-packages/aiomysql/connection.py", line 521, in _connect
    raise OperationalError(2003,
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'xxxxx.rds.amazonaws.com'")

it works with python3.8

**Comment by albertyw** [comment]
This is a duplicate of #505
